# Generated by Django 3.1 on 2020-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('vercode', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
